"""SQLAlchemy ORM models for GeoLux platform.

All tables are additive to the existing Stargate schema. Table names are
prefixed with 'glx_' to avoid collisions.
"""

import enum

from sqlalchemy import (
    Column,
    DateTime,
    Enum,
    Float,
    Index,
    Integer,
    String,
    Text,
    Boolean,
)
from sqlalchemy.dialects.postgresql import JSON, UUID

from db.database import Base


# ── Enums ──────────────────────────────────────────────────────────────


class StabilityMethod(str, enum.Enum):
    ACTIVATION_VARIANCE = "activation_variance"
    TOKEN_PROBABILITY = "token_probability"
    PERPLEXITY = "perplexity"
    LOGIT_ENTROPY = "logit_entropy"


class StabilityState(str, enum.Enum):
    STABLE_PASS = "stable_pass"
    UNSTABLE_PASS = "unstable_pass"
    STABLE_FAIL = "stable_fail"
    UNSTABLE_FAIL = "unstable_fail"


class AssertionType(str, enum.Enum):
    THRESHOLD = "threshold"
    BOOLEAN = "boolean"
    RANGE = "range"
    PATTERN = "pattern"
    COMPOSITE = "composite"
    SEMANTIC = "semantic"


class Severity(str, enum.Enum):
    CRITICAL = "critical"
    MAJOR = "major"
    MINOR = "minor"


class ClassificationResult(str, enum.Enum):
    PASS = "pass"
    FAIL = "fail"
    INCONCLUSIVE = "inconclusive"
    UNCLASSIFIABLE = "unclassifiable"


class TierAssignment(str, enum.Enum):
    NANO = "nano"
    MICRO = "micro"
    MACRO = "macro"


class Substrate(str, enum.Enum):
    CPU = "cpu"
    XEON6 = "xeon6"
    GAUDI = "gaudi"


class TriggerType(str, enum.Enum):
    AUTO = "auto"
    MANUAL = "manual"
    SYSTEM = "system"


class ValidationOutcome(str, enum.Enum):
    VALIDATED = "validated"
    FALSIFIED = "falsified"
    INCONCLUSIVE = "inconclusive"


# ── Geometric Stability ───────────────────────────────────────────────


class LLMStabilityRecord(Base):
    """Per-LLM-call geometric stability measurement."""
    __tablename__ = "glx_llm_stability_records"

    id = Column(Integer, primary_key=True, autoincrement=True)
    call_id = Column(String(255), unique=True, nullable=False, index=True)
    endpoint = Column(String(100), nullable=False, index=True)
    model = Column(String(255), nullable=False)
    stability_score = Column(Float, nullable=False)
    stability_method = Column(Enum(StabilityMethod, values_callable=lambda e: [m.value for m in e]),nullable=False)
    stability_threshold = Column(Float, nullable=False)
    stability_state = Column(Enum(StabilityState, values_callable=lambda e: [m.value for m in e]),nullable=False)
    raw_signal = Column(JSON, nullable=True)
    created_at = Column(DateTime(timezone=True), nullable=False)


# ── Hypothesis Engine ─────────────────────────────────────────────────


class HypothesisRecord(Base):
    """Structured falsifiable hypotheses generated by THE."""
    __tablename__ = "glx_hypotheses"
    __table_args__ = (
        Index("idx_glx_hyp_stability", "geometric_stability_score"),
        Index("idx_glx_hyp_validation", "validation_outcome"),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    hypothesis_id = Column(String(255), unique=True, nullable=False, index=True)
    evidence_bundle_id = Column(String(255), nullable=False, index=True)
    claim = Column(Text, nullable=False)
    testable_conditions = Column(JSON, nullable=False)
    confidence_score = Column(Float, nullable=False)
    geometric_stability_score = Column(Float, nullable=False)
    geometric_stability_method = Column(Enum(StabilityMethod, values_callable=lambda e: [m.value for m in e]),nullable=False)
    geometric_stability_state = Column(Enum(StabilityState, values_callable=lambda e: [m.value for m in e]),nullable=False)
    validation_outcome = Column(Enum(ValidationOutcome, values_callable=lambda e: [m.value for m in e]),nullable=True)
    validated_at = Column(DateTime(timezone=True), nullable=True)
    evidence_snapshot = Column(JSON, nullable=True)
    stale = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime(timezone=True), nullable=False)
    audit_record_id = Column(String(255), nullable=True, index=True)


# ── Constraint Classification ─────────────────────────────────────────


class ConstraintDefinitionRecord(Base):
    """Formal typed constraint definitions for rubric stages."""
    __tablename__ = "glx_constraint_definitions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    constraint_id = Column(String(255), unique=True, nullable=False, index=True)
    constraint_name = Column(String(255), nullable=False)
    stage = Column(String(100), nullable=False, index=True)
    assertion_type = Column(Enum(AssertionType, values_callable=lambda e: [m.value for m in e]), nullable=False)
    assertion_definition = Column(JSON, nullable=False)
    evidence_requirements = Column(JSON, nullable=False)
    severity = Column(Enum(Severity, values_callable=lambda e: [m.value for m in e]), nullable=False)
    remediation_class = Column(String(255), nullable=True)
    geometric_stability_weight = Column(Float, nullable=False, default=0.5)
    version = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime(timezone=True), nullable=False)
    deprecated_at = Column(DateTime(timezone=True), nullable=True)


class ClassificationRecord(Base):
    """Evidence-based constraint classification results."""
    __tablename__ = "glx_classifications"
    __table_args__ = (
        Index("idx_glx_cls_constraint", "constraint_id"),
        Index("idx_glx_cls_result", "result"),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    classification_id = Column(String(255), unique=True, nullable=False, index=True)
    evidence_bundle_id = Column(String(255), nullable=False, index=True)
    constraint_id = Column(String(255), nullable=False, index=True)
    result = Column(Enum(ClassificationResult, values_callable=lambda e: [m.value for m in e]),nullable=False)
    confidence_score = Column(Float, nullable=False)
    geometric_stability_score = Column(Float, nullable=True)
    geometric_stability_state = Column(Enum(StabilityState, values_callable=lambda e: [m.value for m in e]),nullable=True)
    evidence_chain = Column(JSON, nullable=False)
    llm_interpretation_used = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime(timezone=True), nullable=False)
    audit_record_id = Column(String(255), nullable=True, index=True)


# ── LLM-MPC ──────────────────────────────────────────────────────────


class MPCCycleRecord(Base):
    """Model Predictive Control cycle records with full audit trail."""
    __tablename__ = "glx_mpc_cycles"

    id = Column(Integer, primary_key=True, autoincrement=True)
    cycle_id = Column(String(255), unique=True, nullable=False, index=True)
    cluster_id = Column(String(255), nullable=False, index=True)
    horizon = Column(Integer, nullable=False)
    current_state = Column(JSON, nullable=False)
    predictions = Column(JSON, nullable=False)
    candidate_actions = Column(JSON, nullable=False)
    selected_action_id = Column(String(255), nullable=True)
    optimization_score = Column(Float, nullable=True)
    geometric_stability_profile = Column(JSON, nullable=False)
    horizon_adjusted = Column(Boolean, nullable=False, default=False)
    suspended = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime(timezone=True), nullable=False)
    audit_record_id = Column(String(255), nullable=True, index=True)


# ── Deepfield Routing ─────────────────────────────────────────────────


class RoutingDecisionRecord(Base):
    """Deepfield workload routing decisions."""
    __tablename__ = "glx_routing_decisions"
    __table_args__ = (
        Index("idx_glx_route_tier", "tier_assignment"),
        Index("idx_glx_route_substrate", "substrate"),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    routing_id = Column(String(255), unique=True, nullable=False, index=True)
    workload_id = Column(String(255), nullable=False, index=True)
    workload_description = Column(JSON, nullable=False)
    tier_assignment = Column(Enum(TierAssignment, values_callable=lambda e: [m.value for m in e]),nullable=False)
    substrate = Column(Enum(Substrate, values_callable=lambda e: [m.value for m in e]),nullable=False)
    confidence_score = Column(Float, nullable=False)
    geometric_stability_score = Column(Float, nullable=True)
    geometric_stability_state = Column(Enum(StabilityState, values_callable=lambda e: [m.value for m in e]),nullable=True)
    policy_rule_applied = Column(String(255), nullable=True)
    override = Column(Boolean, nullable=False, default=False)
    override_reason = Column(String(500), nullable=True)
    override_operator = Column(String(255), nullable=True)
    created_at = Column(DateTime(timezone=True), nullable=False)
    audit_record_id = Column(String(255), nullable=True, index=True)


class NanoObsRecord(Base):
    """NanoObs threshold observation and drift detection records."""
    __tablename__ = "glx_nano_obs_records"
    __table_args__ = (
        Index("idx_glx_nobs_cluster_agent", "cluster_id", "agent_id"),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    observation_id = Column(String(255), unique=True, nullable=False, index=True)
    cluster_id = Column(String(255), nullable=False, index=True)
    agent_id = Column(String(255), nullable=False, index=True)
    threshold_id = Column(String(255), nullable=False)
    observed_value = Column(Float, nullable=False)
    threshold_value = Column(Float, nullable=False)
    drift_detected = Column(Boolean, nullable=False, default=False)
    drift_magnitude = Column(Float, nullable=True)
    adjustment_recommended = Column(Boolean, nullable=False, default=False)
    adjustment_value = Column(Float, nullable=True)
    adjustment_approved = Column(Boolean, nullable=True)
    approved_by = Column(String(255), nullable=True)
    approved_at = Column(DateTime(timezone=True), nullable=True)
    created_at = Column(DateTime(timezone=True), nullable=False)


# ── Audit Events ──────────────────────────────────────────────────────


class AuditEventRecord(Base):
    """Unified audit trail for all GeoLux components."""
    __tablename__ = "glx_audit_events"
    __table_args__ = (
        Index("idx_glx_audit_source", "source_component"),
        Index("idx_glx_audit_type", "event_type"),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    event_id = Column(String(255), unique=True, nullable=False, index=True)
    source_component = Column(String(100), nullable=False)
    event_type = Column(String(100), nullable=False)
    payload_reference = Column(String(255), nullable=True)
    geometric_stability_score = Column(Float, nullable=True)
    operator = Column(String(255), nullable=True)
    trigger_type = Column(Enum(TriggerType, values_callable=lambda e: [m.value for m in e]),nullable=False, default=TriggerType.AUTO)
    created_at = Column(DateTime(timezone=True), nullable=False)


# ── Launchpad Intelligence ────────────────────────────────────────────


class LaunchpadIntelligenceRecord(Base):
    """Provisioning intelligence snapshots."""
    __tablename__ = "glx_launchpad_intelligence"

    id = Column(Integer, primary_key=True, autoincrement=True)
    intelligence_id = Column(String(255), unique=True, nullable=False, index=True)
    intelligence_type = Column(String(100), nullable=False, index=True)
    data_payload = Column(JSON, nullable=False)
    time_window_start = Column(DateTime(timezone=True), nullable=False)
    time_window_end = Column(DateTime(timezone=True), nullable=False)
    confidence = Column(Float, nullable=True)
    created_at = Column(DateTime(timezone=True), nullable=False)
